//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasklist
    {
        public int taskID { get; set; }
        public string task { get; set; }
        public string descrip { get; set; }
        public System.DateTime dateby { get; set; }
        public bool status { get; set; }
    }
}
